application:
  name: hasura-api
  project: hasura-con
  cloud_region: aws/us-east-2
databases:
- type: postgresql
  version: "11.8.0"
  name: my-postgresql-db
routers:
- name: main
  custom_domains:
  - branch: master
    domain: hasura-api.qvy.io
  routes:
  - application_name: hasura-api
    paths:
    - /*
